Trans pride version
yusitnikov/sudokupad-bet-tree pull request #1
Opened 2023-02-12 17:43 UTC by emckee2006

2023-02-12 20:48 UTC, yusitnikov requested changes
Hi @emckee2006 , good work!

I know that several people are already using this extension, and I don't want to force them to use the pride version. So if you want this PR to be merged, please make the button configurable. Of course, merging the PR is not a must, because people could just install the themed script from your fork instead of mine.

2023-02-12 20:48 UTC, yusitnikov commented on sudokupad-bet-tree.user.js
> +// @updateURL    https://github.com/emckee2006/sudokupad-bet-tree/raw/main/sudokupad-bet-tree.user.js
I can't merge the PR with a modified `updateURL`.

2023-02-12 20:48 UTC, yusitnikov commented on sudokupad-bet-tree.user.js
> -	const renderTree = (renderer, scaleCoeff, offsetX, offsetY) => {
The job of this function was to ensure that the bet tree itself and the button's icon look exactly the same, and I'd like to leave it this way.

2023-02-12 20:50 UTC, yusitnikov commented
P.S. The merge conflicts are because I just removed the Christmas theming. I guess that it's the time :D

2023-02-12 21:15 UTC, emckee2006 commented
That's ok... I made it because Zeta was wanting one of those to replace
Christmas... How would I make it configurable?

On Sun, Feb 12, 2023, 3:50 PM Yuri Sitnikov ***@***.***>
wrote:

> P.S. The merge conflicts are because I just removed the Christmas theming.
> I guess that it's the time :D
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yusitnikov/sudokupad-bet-tree/pull/1#issuecomment-1427129358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLFC4F275V4HV425OLWDU3WXFEIXANCNFSM6AAAAAAUZOLRFU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-12 21:38 UTC, yusitnikov commented
> That's ok... I made it because Zeta was wanting one of those to replace Christmas... How would I make it configurable?

You can use the `Framework.addSetting` API to add a new toggle or select-box to the settings. See https://sudokupad.app/tool-letter.js for example.

2023-02-13 21:24 UTC, yusitnikov commented
And now the pride theme is in too, so I'm closing the PR. Please write here or open an issue if there's something wrong with it

2023-02-13 21:24 UTC, closed without merging